name: C/C++ CI

on:
  push:
    branches: [ flatcar-master ]
  pull_request:
    branches: [ flatcar-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt install -y libblkid-dev libext2fs-dev libmount-dev curl unzip libdbus-glib-1-dev protobuf-compiler libbz2-dev libgflags-dev libssl-dev libgoogle-glog-dev libcurl4-openssl-dev libxml2-dev libprotobuf-dev libgtest-dev
    - name: prep rootdev
      run: |
        curl -sSL -o /tmp/seismograph.zip https://github.com/kinvolk/seismograph/archive/flatcar-master.zip
        cd /tmp && unzip /tmp/seismograph.zip && cd seismograph-flatcar-master && sh autogen.sh && ./configure && make && sudo make install
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
      ## this unittest needs to link against -lgmock and -lgtest, which are not provided in the 'googletest' package. Need a next step here...
      #- name: make check
      #run: make check
      #- name: make distcheck
      #run: make distcheck
