name: C/C++ CI

on:
  push:
    branches: [ flatcar-master ]
  pull_request:
    branches: [ flatcar-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt install -y libblkid-dev libext2fs-dev libmount-dev curl unzip
    - name: prep rootdev
      run: |
        curl -o /tmp/seismograph.zip https://github.com/kinvolk/seismograph/archive/flatcar-master.zip
        cd /tmp && unzip /tmp/seismograph.zip && cd seismograph-flatcar-master && sh autogen.sh && ./configure && make && make install
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
